### PR TITLE
Import sheet feature v1

### PR DESCRIPTION
**Pull request by IlanIwumbwe**
This is my first draft of the import sheet feature. I am aware of a bug when importing multiple files, the big import button at the bottom isn't enabled even though decisions are made on all files. I wanted to submit the PR anyway for code quality feedback.

Ideas for extensions:
- Currently, I only check that sheets exist in destination directory by their name, but I think it would be better to do the following: 1. Get the 2 instances of sheets and compare signatures. 2. If signatures match, then allow overwrite, if they don't disable overwrite.
- For each sheet I import, get all its dependencies and offer them for import as well
- It's highly likely that someone will import a series of sheets into an empty/almost empty directory, which means that they could be a situation where all sheets need to be imported as is. So a button that does 'Import all as is' could be helpful.

### CODE REVIEW

**Comment by tomcl** [comment]
Feedback on code:
getDependents is not a safe function – it should be made so it cannot crash and operation specified precisely (it needs an XML comment anyway).

General comment – remember the dialog functions can all be cancelled – cope with this. (Maybe you do – I have not checked). Similarly any I/O function can not work.

getSheetInfo

  *   exists is weird – it appears to be input (as a function) and output (as a Boolean of code. Don’t shadow names like that. And exists is too short and general to be a good global input. (If you are using List.exists by opening List package don’t. It is annoying, but better to kep the qiualification).
  *   Let not needed except to name results…
  *   Results should be generated (without let) and returned as an anonymous record with names more informative than exists. Maybe projectHasSheet
  *   Even better, return just one value which is an option. Not exists corresponds to None.

Line 957 is too long.
Type not needed.
getImportDecisions <| model.PopupDialogData)
does not need <| - it is a function call and parameter is a single element.
In any case that expression could be made into a local with a suitable name, probably a good idea – it reads a bit weird at the moment.
Or, the anon fun could beturned into a named fun.

957 vs 963. You have the SAME EXPRESSION written different ways. And, anyway, it surely merits being a local given a name and computed once given it is used twice and probably has a useful name?

Line 980 ,996, etc use interpolated strings

Line 1052/1054.
Decision used both for the pair and the value – confusing. Need different identifiers for the different things.

1055 – 1066 – this long match is really much simpler, it can return the only thing that changes (the filename) which can then be used. Could do this with a let, or an anonymous function after. Note the give-away repeated code.


Feedback on features below

From: Ilan Iwumbwe ***@***.***>
Sent: Sunday, August 13, 2023 7:51 PM
To: tomcl/issie ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tomcl/issie] Import sheet feature v1 (PR #355)


This is my first draft of the import sheet feature. I am aware of a bug when importing multiple files, the big import button at the bottom isn't enabled even though decisions are made on all files. I wanted to submit the PR anyway for code quality feedback.

Ideas for extensions:

  *   Currently, I only check that sheets exist in destination directory by their name, but I think it would be better to do the following: 1. Get the 2 instances of sheets and compare signatures. 2. If signatures match, then allow overwrite, if they don't disable overwrite.
OK – you must say why the overwrite is disabled.

  *   For each sheet I import, get all its dependencies and offer them for import as well
Agreed – and say whether there are any missing dependencies (but allow this).

  *   It's highly likely that someone will import a series of sheets into an empty/almost empty directory, which means that they could be a situation where all sheets need to be imported as is. So a button that does 'Import all as is' could be helpful.
Use good defaults. In this case there is no need to explicitly say what will be done if there is no over-writing. There can still be a confirmation of what will happen (all sheets imported) but the OK button will be all that is needed. In general you only need to give the user decisions when these are needed.

Good defaults should mean that when importing something simple, what the user sees and does is simple.
________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/tomcl/issie/pull/355

Commit Summary

  *   a10c766<https://github.com/tomcl/issie/pull/355/commits/a10c766fbca7ac61421362d2c84ab8c219a67ffa> Import sheet feature has most functionality, but bug when multiple sheets are imported

File Changes

(7 files<https://github.com/tomcl/issie/pull/355/files>)

  *   M src/Renderer/DrawBlock/PopupHelpers.fs<https://github.com/tomcl/issie/pull/355/files#diff-3ce9a587085acfbf90b7cdcb2dd13c85861e1908d3c58c8de0b42b4a107fc17c> (2)
  *   M src/Renderer/Interface/FilesIO.fs<https://github.com/tomcl/issie/pull/355/files#diff-dbb5cc93fd6775159374ac7bf7256501688ab432619cdee38bc6a5e76cf81c4d> (55)
  *   M src/Renderer/Model/ModelType.fs<https://github.com/tomcl/issie/pull/355/files#diff-cfe8e5546fa1c6f63a8e917b98b141b77c32647715e21353807916c8cbfde290> (8)
  *   M src/Renderer/UI/FileMenuView.fs<https://github.com/tomcl/issie/pull/355/files#diff-9de92bcf529f754c30d5396b85a5dc50380428a9a219107fe6fb92764b070ea1> (185)
  *   M src/Renderer/UI/MainView.fs<https://github.com/tomcl/issie/pull/355/files#diff-114c8ed17f210dc54b8be593909aba92a415ed573cd347dc937ea74af6548bbf> (1)
  *   M src/Renderer/UI/Update.fs<https://github.com/tomcl/issie/pull/355/files#diff-d918541fd75b1595039511dd968d97c77c536ff08c94bd303f34fbd02871204f> (24)
  *   M src/Renderer/UI/UpdateHelpers.fs<https://github.com/tomcl/issie/pull/355/files#diff-6978f5883281acadc8595b2436d550bde5b668e3e71a1370ea3a3d6e0a19ce48> (3)

Patch Links:

  *   https://github.com/tomcl/issie/pull/355.patch
  *   https://github.com/tomcl/issie/pull/355.diff

**Comment by IlanIwumbwe** [comment]
Thank you for the feedback, it will be implemented in my next commit.

**Comment by tomcl** [comment]
Hang on Ilan, although that type of problem can be worked through – I’ve done it myself – it would be quicker if I help you. The stuff about timing in Issie is always difficult till you understand it – and it is nowhere well documented.

Do you want a quick Team meeting now?

Tom

**Comment by IlanIwumbwe** [comment]
Sorry for taking so long to get back to you. I have it now working sheets where a decision needs to be made. Where the user tries to import more than one sheet where a decision doesn't need to be made, it doesn't work. Testing it tells me that it doesn't add all such sheets to the map, so Issie thinks not all decisions have been made. Combinations of imports where more than one sheet that doesn't require decisions is chosen don't work either.

**Comment by tomcl** [comment]
So – the question is exactly what sequence of state updates is happening.

I think you have a problem with your definition of state. You need:

Sheet exists to be imported – no decision yet made
Sheet exists to be imported – decision A
Sheet exists to be imported – decision B

You are not modelling this state properly and working out state transitions.

Like you would in DECA state machines 😊

But I am pretty sure the datatype is a map of a Boolean (or other two-choice type) option (3 states) not two states.

Do you need a call about this? Or does it make sense?

**Comment by tomcl** [comment]
There is a lesson here:

Programming requires you to analyse and fully understand what you are doing. Not just do things intuitively. So – write down the required state changes.

**Comment by IlanIwumbwe** [comment]
I think I need a call about this, thank you

**Pull request closed without merging**
